version: '3'
services:
  anaconda:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
      - "8000:8000"
    command: /bin/bash -c "source activate base && jupyter notebook --notebook-dir=/app --ip='*' --port=8888 --no-browser --allow-root"
    networks:
      - backend

  mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: python_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - python_db:/var/lib/mysql
    networks:
      - backend

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    networks:
      - backend

volumes:
  python_db:
    driver: local

networks:
  backend:
    driver: bridge